<?php

/**
 * Implements hook_block_info().
 *
 * This hook declares what blocks are provided by the module.
 */
function teach_it_dframe_config_block_info() {
  $blocks['contact_information'] = array(
    'info' => t('Header contact information'),
    'status' => TRUE,
    'region' => 'user_first',  // Not usually provided.
    //'visibility' => BLOCK_VISIBILITY_LISTED,  // Not usually provided.
    //'pages' => 'node/*', // Not usually provided here.
  );
  
  $blocks['social_information'] = array(
    'info' => t('Header social information'),
    'status' => TRUE,
    'region' => 'user_second',  // Not usually provided.
    //'visibility' => BLOCK_VISIBILITY_LISTED,  // Not usually provided.
    //'pages' => 'node/*', // Not usually provided here.
  );

  return $blocks;
}

/**
 * Implements hook_block_view().
 *
 * This hook generates the contents of the blocks themselves.
 */
function teach_it_dframe_config_block_view($delta = '') {
  
  //The $delta parameter tells us which block is being requested.
  switch ($delta) {
    case 'contact_information':
      //$block['subject'] = t('Title of second block (example_empty)');
      $block['content'] = block_teach_it_dframe_contents($delta);
      break;
    case 'social_information':
      //$block['subject'] = t('Title of second block (example_empty)');
      $block['content'] = block_teach_it_dframe_contents($delta);
      break;
  }
  return $block;
}

/**
 * A module-defined block content function.
 */
function block_teach_it_dframe_contents($which_block) {
  switch ($which_block) {
    case 'contact_information':
      return array('#markup' => '<p class="contact-information"><span>E: ' . theme_get_setting('email', 'teach_it_dframe') . '</span>&emsp;<span>T: ' . theme_get_setting('mobile_phone', 'teach_it_dframe') . '</span></p>');
    case 'social_information':
      return array('#markup' => social_information_html());
  }
}

function social_information_html() {
  $tag = '';
  $twitter_url = theme_get_setting('twitter_url', 'teach_it_dframe');
  if($twitter_url !== '') {
    $tag .= '<a href="' . $twitter_url . '" class="twitter" title="' . t('Twitter') . '">' . t('Twitter') . '</a>';
  }
  $facebook_url = theme_get_setting('facebook_url', 'teach_it_dframe');
  if($facebook_url !== '') {
    $tag .= '<a href="' . $facebook_url . '" class="facebook" title="' . t('Facebook') . '">' . t('Facebook') . '</a>';
  }
  $google_plus_url = theme_get_setting('google_plus_url', 'teach_it_dframe');
  if($google_plus_url !== '') {
    $tag .= '<a href="' . $google_plus_url . '" class="gplus" title="' . t('Gplus') . '">' . t('G+') . '</a>';
  }
  $instagram_url = theme_get_setting('instagram_url', 'teach_it_dframe');
  if($instagram_url !== '') {
    $tag .= '<a href="' . $linkedin_url . '" class="instagram" title="' . t('instagram') . '">' . t('Instagram') . '</a>';
  }
  $pinterest_url = theme_get_setting('pinterest_url', 'teach_it_dframe');
   if($pinterest_url !== '') {
    $tag .= '<a href="' . $flickr_url . '" class="pinterest" title="' . t('pinterest') . '">' . t('Pinterest') . '</a>';
  }
  $youtube_url = theme_get_setting('youtube_url', 'teach_it_dframe');
   if($youtube_url !== '') {
    $tag .= '<a href="' . $youtube_url . '" class="youtube" title="' . t('youtube') . '">' . t('Youtube') . '</a>';
  }
  
  $html = '<p class="pull-right socialIcons">' . $tag . '</p>';
  
  return $html;
}